#!/bin/bash

mkdir $HOME/.cache
mkdir $HOME/.cache/awesome
sleep 2 && $HOME/.config/awesome/autorun.sh &

export XDG_DESKTOP_DIR="${HOME}"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DOCUMENTS_DIR="${HOME}/files/docs"
export XDG_DOWNLOAD_DIR="${HOME}/files/downloads"
export XDG_MUSIC_DIR="${HOME}/files/music"
export XDG_PICTURES_DIR="${HOME}/files/images"
export XDG_VIDEOS_DIR="${HOME}/files/videos"
export XDG_PUBLICSHARE_DIR="/non/existent"

exec awesome >> $HOME/.cache/awesome/stdout 2>> $HOME/.cache/awesome/stderr
