#!/bin/bash

mkdir -p $HOME/.cache/herbstluftwm

export XDG_DESKTOP_DIR="${HOME}"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DOCUMENTS_DIR="${HOME}/files/docs"
export XDG_DOWNLOAD_DIR="${HOME}/files/downloads"
export XDG_MUSIC_DIR="${HOME}/files/music"
export XDG_PICTURES_DIR="${HOME}/files/images"
export XDG_VIDEOS_DIR="${HOME}/files/videos"
export XDG_PUBLICSHARE_DIR="/non/existent"

exec herbstluftwm  >> $HOME/.cache/herbstluftwm/stdout 2>> $HOME/.cache/herbstluftwm/stderr

