options:
  shell:
    home:
      fileName: powershell.exe
      arguments:
      - -Command
      - ${command}
      replacements:
        '"': "'"
    work:
      fileName: powershell.exe
      arguments:
      - -Command
      - ${command}
      replacements:
        '"': "'"
    vm:
      fileName: bash
      arguments:
      - -c
      - ${command}
      replacements:
        '"': '\"'
  profiles:
  - home
  - work
  - vm
  packageCommand:
    home: choco install -y '${package}'
    work: echo 'Id install ${package} now but I dont have a package manager installed'
    vm: pacman -S -y '${package}'
  symlinkCommand:
    home: New-Item -Path '${destination}' -ItemType SymbolicLink -Value '${source}'
    work: New-Item -Path '${destination}' -ItemType SymbolicLink -Value '${source}'
    vm: ln -s '${source}' '${destination}'
  encryptCommand:
    windows: gpg --armor --output '${destination}' --encrypt --recipient lyze@owl.sh '${source}'
    ubuntu: gpg --armor --output '${destination}' --encrypt --recipient lyze@owl.sh '${source}'
    mac: gpg --armor --output '${destination}'' --encrypt --recipient lyze@owl.sh '${source}'
  decryptCommand:
    windows: gpg --armor --output '${destination}'' --decrypt '${source}'
    ubuntu: gpg --armor --output '${destination}'' --decrypt '${source}'
    mac: gpg --armor --output '${destination}'' --decrypt '${source}'
  baseDirectory: dotfiles
commands:
  EnablePsScripts:
    home: Set-ExecutionPolicy RemoteSigned
    work: Set-ExecutionPolicy RemoteSigned
  InstallVsCodeExtensions:
    home: ./dotfiles/Commands/InstallVsCodeExtensions.ps1
    work: ./dotfiles/Commands/InstallVsCodeExtensions.ps1
  ImportPublicGpgKey:
    home: gpg --recv-keys 0103354801C36F14
    work: gpg --recv-keys 0103354801C36F14
    vm: gpg --recv-keys 0103354801C36F14
packages: {}
files:
  PowerShellProfile:
    source: Windows/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1
    destinations:
      default: ${home}/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1
    exclude:
    - vm
    attribute: Generic
    commands:
    - EnablePsScripts
    - ImportPublicGpgKey
    randoms:
      ATEC1531: {}
  CodeSettings:
    source: CrossPlatform/Code/User/settings.json
    destinations:
      vm: ${home}/.config/Code/User/settings.json
      default: ${home}/AppData/Roaming/Code/User/settings.json
    exclude: []
    attribute: Generic
    commands:
    - InstallVsCodeExtensions
    randoms:
      ATEC1531: {}
  gitattributes:
    source: CrossPlatform/Git/.gitattributes
    destinations:
      default: ${home}/.gitattributes
    exclude: []
    attribute: Generic
    commands: []
    randoms: {}
  gitconfig:
    source: CrossPlatform/Git/.gitconfig
    destinations:
      default: ${home}/.gitconfig
    exclude: []
    attribute: Generic
    commands: []
    randoms: {}
  gitignore:
    source: CrossPlatform/Git/.gitignore
    destinations:
      default: ${home}/.gitignore
    exclude: []
    attribute: Generic
    commands: []
    randoms: {}
directories:
  C4dScripts:
    source: Windows/AppData/Roaming/MAXON/Cinema 4D R19/library/scripts
    destinations:
      default: ${home}/AppData/Roaming/MAXON/Cinema 4D R19_${random_c4d}/library/scripts
    exclude:
    - vm
    commands: []
    attribute: Generic
    randoms:
      ATEC1531:
        c4d: BFE04C39
  C4dLayout:
    source: Windows/AppData/Roaming/MAXON/Cinema 4D R19/library/layout
    destinations:
      default: ${home}/AppData/Roaming/MAXON/Cinema 4D R19_${random_c4d}/library/layout
    exclude:
    - vm
    commands: []
    attribute: Generic
    randoms:
      ATEC1531:
        c4d: BFE04C39
