actions:
  vim-plug-run: nvim +PlugInstall
  vim-plug-setup: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_fonts:
    dst: ~/.fonts
    link: true
    src: fonts
  d_functions:
    dst: ~/.config/fish/functions
    link: true
    src: config/fish/functions
  d_herbstluftwm:
    dst: ~/.config/herbstluftwm
    link: true
    src: config/herbstluftwm
  d_mutt:
    dst: ~/.config/mutt
    src: config/mutt
  d_owl:
    dst: ~/.config/owl
    link: true
    src: config/owl
  d_owlbin:
    dst: ~/.config/owl/scripts/bin
    link: true
    src: config/owl/scripts/bin
  d_prompt:
    dst: ~/.config/fish/prompt
    link: true
    src: config/fish/prompt
  d_themes:
    dst: ~/.themes
    link: true
    src: themes
  f_chunkwmrc:
    dst: ~/.chunkwmrc
    src: chunkwmrc
  f_compton.conf:
    dst: ~/.config/compton.conf
    link: true
    src: config/compton.conf
  f_config.fish:
    dst: ~/.config/fish/config.fish
    link: true
    src: config/fish/config.fish
  f_config.json:
    dst: ~/.config/Mstdn/config.json
    link: true
    src: config/Mstdn/config.json
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    link: true
    src: config/dunst/dunstrc
  f_git-pass-mapping.ini:
    dst: ~/.config/pass-git-helper/git-pass-mapping.ini
    src: config/pass-git-helper/git-pass-mapping.ini
  f_gitattributes:
    dst: ~/.gitattributes
    link: true
    src: gitattributes
  f_gitconfig:
    dst: ~/.gitconfig
    link: true
    src: gitconfig
  f_gitignore:
    dst: ~/.gitignore
    link: true
    src: gitignore
  f_gpg.conf:
    dst: ~/.gnupg/gpg.conf
    src: gnupg/gpg.conf
    link: true
  f_gtkrc-2.0:
    dst: ~/.gtkrc-2.0
    link: true
    src: gtkrc-2.0
  f_hosts:
    dst: /etc/hosts
    src: etc/hosts
  f_init.vim:
    actions:
    - vim-plug-setup
    - vim-plug-run
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_issue:
    dst: /etc/issue
    src: etc/issue
  f_kitty.conf:
    dst: ~/.config/kitty/kitty.conf
    link: true
    src: config/kitty/kitty.conf
  f_known_hosts:
    dst: ~/.ssh/known_hosts
    link: true
    src: ssh/known_hosts
  f_mailcap:
    dst: ~/.mailcap
    link: true
    src: mailcap
  f_mimeapps.list:
    dst: ~/.config/mimeapps.list
    link: false
    src: config/mimeapps.list
  f_mopidy.conf:
    dst: ~/.config/mopidy/mopidy.conf
    src: config/mopidy/mopidy.conf
  f_ncmpcpp_config:
    dst: ~/.ncmpcpp/config
    link: true
    src: ncmpcpp/config
  f_rofi-pass_config:
    dst: ~/.config/rofi-pass/config
    link: true
    src: config/rofi-pass/config
  f_rofi_config:
    dst: ~/.config/rofi/config
    link: true
    src: config/rofi/config
  f_settings.ini:
    dst: ~/.config/gtk-3.0/settings.ini
    link: true
    src: config/gtk-3.0/settings.ini
  f_skhdrc:
    dst: ~/.skhdrc
    link: true
    src: skhdrc
  f_ssh_config:
    dst: ~/.ssh/config
    link: true
    src: ssh/config
  f_urlview_lin:
    dst: ~/.urlview
    link: true
    src: urlview_lin
  f_urlview_mac:
    dst: ~/.urlview
    link: true
    src: urlview_mac
  f_urlview_wsl:
    dst: ~/.urlview
    link: true
    src: urlview_wsl
  f_xinitrc:
    dst: ~/.xinitrc
    link: true
    src: xinitrc
profiles:
  mac:
    dotfiles:
    - d_owlbin
    - f_gitattributes
    - f_git-pass-mapping.ini
    - f_gitconfig
    - f_gitignore
    - f_init.vim
    - f_config.fish
    - d_functions
    - d_prompt
    - d_mutt
    - f_skhdrc
    - f_chunkwmrc
    - f_urlview_mac
    - f_kitty.conf
    - f_gpg.conf
  ovo:
    dotfiles:
    - f_gpg.conf
    - f_init.vim
    - f_xinitrc
    - f_ssh_config
    - f_known_hosts
    - f_compton.conf
    - f_config.fish
    - f_mimeapps.list
    - d_fonts
    - f_gitattributes
    - f_gitconfig
    - f_gitignore
    - f_ncmpcpp_config
    - f_mailcap
    - f_rofi_config
    - f_settings.ini
    - f_gtkrc-2.0
    - d_themes
    - d_owl
    - d_mutt
    - f_urlview_lin
    - d_functions
    - f_mopidy.conf
    - d_prompt
    - f_rofi-pass_config
    - f_kitty.conf
    - d_herbstluftwm
    - f_dunstrc
    - f_config.json
    - f_git-pass-mapping.ini
  sudo:
    dotfiles:
    - f_issue
    - f_hosts
  wsl:
    dotfiles:
    - f_gitattributes
    - f_gitconfig
    - f_gitignore
    - f_init.vim
    - f_config.fish
    - d_functions
    - d_prompt
    - d_mutt
    - f_urlview_wsl
    - f_gpg.conf
    - d_owlbin
    - f_git-pass-mapping.ini
