actions:
  vim-plug-run: nvim +PlugInstall
  vim-plug-setup: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_awesome:
    dst: ~/.config/awesome
    src: config/awesome
  d_fonts:
    dst: ~/.fonts
    src: fonts
  d_functions:
    dst: ~/.config/fish/functions
    src: config/fish/functions
  d_herbstluftwm:
    dst: ~/.config/herbstluftwm
    src: config/herbstluftwm
  d_mutt:
    dst: ~/.config/mutt
    src: config/mutt
  d_owl:
    dst: ~/.config/owl
    src: config/owl
  d_owlbin:
    dst: ~/.config/owl/scripts/bin
    src: config/owl/scripts/bin
  d_prompt:
    dst: ~/.config/fish/prompt
    src: config/fish/prompt
  d_themes:
    dst: ~/.themes
    src: themes
  f_chunkwmrc:
    dst: ~/.chunkwmrc
    src: chunkwmrc
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_config.fish:
    dst: ~/.config/fish/config.fish
    src: config/fish/config.fish
  f_gitattributes:
    dst: ~/.gitattributes
    src: gitattributes
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gitignore:
    dst: ~/.gitignore
    src: gitignore
  f_gtkrc-2.0:
    dst: ~/.gtkrc-2.0
    src: gtkrc-2.0
  f_init.vim:
    actions:
    - vim-plug-setup
    - vim-plug-run
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_issue:
    dst: /etc/issue
    src: etc/issue
  f_kitty.conf:
    dst: ~/.config/kitty/kitty.conf
    src: config/kitty/kitty.conf
  f_known_hosts:
    dst: ~/.ssh/known_hosts
    src: ssh/known_hosts
  f_mailcap:
    dst: ~/.mailcap
    src: mailcap
  f_mimeapps.list:
    dst: ~/.config/mimeapps.list
    src: config/mimeapps.list
  f_mopidy.conf:
    dst: ~/.config/mopidy/mopidy.conf
    src: config/mopidy/mopidy.conf
  f_mpv.conf:
    dst: ~/.config/mpv/mpv.conf
    src: config/mpv/mpv.conf
  f_msmtprc:
    dst: ~/.msmtprc
    src: msmtprc
  f_ncmpcpp_config:
    dst: ~/.ncmpcpp/config
    src: ncmpcpp/config
  f_offlineimaprc:
    dst: ~/.offlineimaprc
    src: offlineimaprc
  f_rofi-pass_config:
    dst: ~/.config/rofi-pass/config
    src: config/rofi-pass/config
  f_rofi_config:
    dst: ~/.config/rofi/config
    src: config/rofi/config
  f_rtv.cfg:
    dst: ~/.config/rtv/rtv.cfg
    src: config/rtv/rtv.cfg
  f_settings.ini:
    dst: ~/.config/gtk-3.0/settings.ini
    src: config/gtk-3.0/settings.ini
  f_skhdrc:
    dst: ~/.skhdrc
    src: skhdrc
  f_ssh_config:
    dst: ~/.ssh/config
    src: ssh/config
  f_streamlink_config:
    dst: ~/.config/streamlink/config
    src: config/streamlink/config
  f_termite_config:
    dst: ~/.config/termite/config
    src: config/termite/config
  f_urlview_lin:
    dst: ~/.urlview
    src: urlview_lin
  f_urlview_mac:
    dst: ~/.urlview
    src: urlview_mac
  f_urlview_wsl:
    dst: ~/.urlview
    src: urlview_wsl
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
profiles:
  mac:
    dotfiles:
    - d_owlbin
    - f_gitattributes
    - f_gitconfig
    - f_gitignore
    - f_init.vim
    - f_config.fish
    - d_functions
    - d_prompt
    - d_mutt
    - f_skhdrc
    - f_chunkwmrc
    - f_urlview_mac
    - f_kitty.conf
  ovo:
    dotfiles:
    - f_init.vim
    - f_xinitrc
    - f_ssh_config
    - f_known_hosts
    - f_compton.conf
    - f_config.fish
    - f_mimeapps.list
    - f_mpv.conf
    - f_termite_config
    - d_fonts
    - f_gitattributes
    - f_gitconfig
    - f_gitignore
    - f_ncmpcpp_config
    - f_mailcap
    - f_vimrc
    - f_rtv.cfg
    - f_streamlink_config
    - f_rofi_config
    - f_settings.ini
    - f_gtkrc-2.0
    - d_themes
    - d_owl
    - d_awesome
    - d_mutt
    - f_urlview_lin
    - f_msmtprc
    - f_offlineimaprc
    - d_functions
    - f_mopidy.conf
    - d_prompt
    - f_rofi-pass_config
    - f_kitty.conf
    - d_herbstluftwm
  sudo:
    dotfiles:
    - f_issue
  wsl:
    dotfiles:
    - f_gitattributes
    - f_gitconfig
    - f_gitignore
    - f_init.vim
    - f_config.fish
    - d_functions
    - d_prompt
    - d_mutt
    - f_urlview_wsl
    - d_owlbin
