#!/usr/bin/env bash

# Functions {{{
function tryExecute {
    file="$1"

    echo "Trying to execute $file"
    cat "$file"
    if [ -f "$file" ] ; then
        source "$file"
    fi
}
# }}}

echo Running on "$DISPLAY"

echo "Sourcing variables"
source $HOME/.config/herbstluftwm/helpers/gruvbox.sh
source $HOME/.config/herbstluftwm/variables

echo "Sourcing functions"
source $HOM£/.config/herbstluftwm/helpers/hc.sh
source $HOME/.config/herbstluftwm/helpers/monitorStuff.sh


echo "Sending reload hook"
hc emit_hook reload

echo "Setting settings"
source $HOME/.config/herbstluftwm/settings

tryExecute "$HOME/.config/herbstluftwm/specifics/${HOSTNAME}_pre"

if hc silent ! get_attr my_not_first_autostart ; then
    echo "First time run, setting up tags"
    source $HOME/.config/herbstluftwm/monitorSetup

    echo "Setting up keybinds"
    source $HOME/.config/herbstluftwm/keybindings
    echo "Setting up mousebinds"
    source $HOME/.config/herbstluftwm/mousebindings
fi

echo "Running global setup"
source $HOME/.config/herbstluftwm/specifics/global

tryExecute "$HOME/.config/herbstluftwm/specifics/${HOSTNAME}_post"

echo "Setting up panel"
$HOME/.config/herbstluftwm/lemonbar/panel.sh &

echo "Unlocking"
hc unlock

if hc silent ! get_attr my_not_first_autostart ; then
    echo "Setting up floating tag"
    source ~/.config/herbstluftwm/helpers/floatmon.sh
    $HOME/.config/herbstluftwm/helpers/floatingFocusFix.sh &
fi

hc silent new_attr bool my_not_first_autostart

