#!/usr/bin/env bash


# add default tags
for i in {1..9} ; do
    hc add default-$i
done
hc use default-1
hc merge_tag default 



# detect monitors
hc detect_monitors



# implement proper tags
monitorCount=$(getMonitorCount)
echo $monitorCount $(getMonitorCount)

for (( monitorIndex=0; monitorIndex<$monitorCount; monitorIndex++ )) ; do
    for key in ${tagKeys[@]} ; do
        tag=$monitorIndex"_"$key
        previousTag=$((($key - 1 + $tagAmount) % $tagAmount))
        nextTag=$((($key + 1) % $tagAmount))
        hc and + add "$tag" \
               + ! silent get_attr tags.by-name."$tag".my_monitor \
               + chain , new_attr int tags.by-name."$tag".my_monitor \
                       , set_attr tags.by-name."$tag".my_monitor $monitorIndex \
                       , new_attr string tags.by-name."$tag".my_previous_tag \
                       , set_attr tags.by-name."$tag".my_previous_tag "$previousTag"\
                       , new_attr string tags.by-name."$tag".my_next_tag \
                       , set_attr tags.by-name."$tag".my_next_tag "$nextTag" \
                       , new_attr int tags.by-name."$tag".my_monitor_index \
                       , set_attr tags.by-name."$tag".my_monitor_index "$key"

        hc chain , keybind "$Mod-$key" sprintf MONITOR %s_$key tags.focus.my_monitor use MONITOR \
                 , keybind "$Mod-Shift-$key" sprintf MONITOR %s_$key tags.focus.my_monitor move MONITOR
    done
    hc chain , focus_monitor $monitorIndex \
             , use $monitorIndex"_1"
done

# delete default tags
for i in {1..9} ; do
    hc merge_tag default-$i
done

