#!/usr/bin/env bash

Mod=Mod4
terminal=xfce4-terminal

tagKeys=( {1..9} )                                                                                                            
tagAmount=${#tagKeys[@]}

