#!/usr/bin/env bash

if hc silent ! get_attr my_not_first_autostart ; then
    hc load 2_1 '(split horizontal:0.650000:1 (clients vertical:0) (split vertical:0.500000:0 (clients vertical:0) (clients vertical:0)))'
    hc load 0_1 '(split vertical:0.500000:0 (clients vertical:0 0x4200014) (clients horizontal:1 0x3800014 0x3e00014))'

    # left desktop
    hc rule class=htop tag=0_1 index=11
    hc rule class=pulsemixer tag=0_1 index=10

    spotify &
    kitty --class htop htop & 
    kitty --class pulsemixer pulsemixer &

    # middle desktop
    hc rule class=neomutt tag=1_8
    hc rule class=obs tag=1_9
    hc rule class=Nextcloud title="Enter Password" hook=NEXTCLOUD
    hc rule class="Pinentry-gtk-2" focus=off hook=FLOAT_DIALOG monitor=$floatingMonitorName tag=$floatingTagName

    kitty --class neomutt neomutt &
    nextcloud &

    # right desktop

    hc rule class=discord tag=2_1 index=0
    hc rule class=Mstdn tag=2_1 index=10
    hc rule class=TelegramDesktop tag=2_1 index=11

    discord-ptb &
    open-mstdn-app &
    /opt/lyze/Telegram/Telegram &

    hc focus_monitor 2
    hc use 2_1
fi

feh --bg-scale "$HOME/.config/herbstluftwm/specifics/wallpapers/middle.png" --bg-scale "$HOME/.config/herbstluftwm/specifics/wallpapers/left.png" --bg-scale "$HOME/.config/herbstluftwm/specifics/wallpapers/right.png"

function setupListeners() {
    hc -i |
    while read -r line ; do
        if [[ "$line" = *"NEXTCLOUD"* ]] ; then
            client="$(echo $line | cut -d ' ' -f3)"
            
            # automate nextcloud window
            xdotool type --window $client $(pass private/cloud.owl.sh/lyze_token)
        fi
    done
} 

setupListeners &
