#!/usr/bin/env bash

if hc silent ! get_attr my_not_first_autostart ; then
    ~/.config/owl/scripts/screenlayout.sh # fix screen layout
    setxkbmap gb # set gb as keyboard layout
    numlockx on # enable numlock
    xsetroot -cursor_name Breeze_Obsidian & # set correct cursor theme
    parcellite & # clipboard manager
fi
