#!/usr/bin/env bash

hc load 2_1 '(split horizontal:0.650000:1 (clients vertical:0) (split vertical:0.500000:0 (clients vertical:0) (clients vertical:0)))'

hc rule class=Xfce4-terminal title=left tag=2_1 index=0
hc rule class=Xfce4-terminal title=top tag=2_1 index=10
hc rule class=Xfce4-terminal title=bottom tag=2_1 index=11

xfce4-terminal --title=left &
xfce4-terminal --title=top &
xfce4-terminal --title=bottom &

hc focus_monitor 2
hc use 2_1
